### ISSUE TITLE
Permission Denied Error

### ISSUE THREAD

**Issue by jonnyleigh** [Mangopay/mangopay2-php-sdk#171] opened 2017-08-21 20:24 UTC
I've had this error occur on two occasions when getting a list of cards registered to a user:

```
<br />
<b>Warning</b>:  file_put_contents(mangotemp/MangoPaySdkStorage.tmp.php) [<a href='function.file-put-contents'>function.file-put-contents</a>]: failed to open stream: Permission denied in <b>/home/w293s11307/public_html/mangopay_api/Libraries/DefaultStorageStrategy.php</b> on line <b>49</b><br />
<br />
<b>Fatal error</b>:  Uncaught exception 'MangoPay\Libraries\Exception' with message 'Cannot put token to file' in /home/w293s11307/public_html/mangopay_api/Libraries/DefaultStorageStrategy.php:51
Stack trace:
#0 /home/w293s11307/public_html/mangopay_api/Libraries/AuthorizationTokenManager.php(46): MangoPay\Libraries\DefaultStorageStrategy-&gt;Store(Object(MangoPay\Libraries\OAuthToken))
#1 /home/w293s11307/public_html/mangopay_api/Libraries/AuthorizationTokenManager.php(33): MangoPay\Libraries\AuthorizationTokenManager-&gt;StoreToken(Object(MangoPay\Libraries\OAuthToken))
#2 /home/w293s11307/public_html/mangopay_api/Libraries/AuthenticationHelper.php(83): MangoPay\Libraries\AuthorizationTokenManager-&gt;GetToken('cdc79767f26f785...')
#3 /home/w293s11307/public_html/mangopay_api/Libraries/AuthenticationHelper.php(27): MangoPay\Libraries\AuthenticationHelper-&gt;GetHttpHeaderStrong()
#4 /home/w293s11307/public_html/mangopay_api/Libraries/RestTool.php(239): MangoPay\Libraries\AuthenticationHelper-&gt;GetHttpHeaderKey()
#5 /home/w293s11307/public_h in <b>/home/w293s11307/public_html/mangopay_api/Libraries/DefaultStorageStrategy.php</b> on line <b>51</b><br />
```

If I delete the file "MangoPaySdkStorage.tmp.php" which is present in the temporary directory then the application continues to work fine.

The temporary directory has permissions 0777

**Comment by mickaelpois** [comment] 2017-08-22 08:36
Hi @jonnyleigh,

It seems you are talking about a known issue. As it is written on our documentation:
> If you experience problems with authentification and/or the temporary token file following an SDK update (particuarly updating to v2.0 of the SDK), you may need to just delete your temporary file (that you specify with $api->Config->TemporaryFolder) - which allows it to be regenerated correctly the next time it's needed

Does this scenario fits with your issue ?

**Comment by jonnyleigh** [comment] 2017-08-22 18:22
Hi @mickaelpois, no the issue I saw was not following an SDK update, but occured "randomly" (i.e. I haven't worked out yet what caused it).
I'll keep an eye on it and report back here if it happens again.  Our application is not yet in production use.
Thanks,

**Comment by mickaelpois** [comment] 2017-08-23 08:00
Hello @jonnyleigh !
Thanks a lot, feedbacks are very welcome !
It could happend when you're switching from one Mangopay client account to another one, but I guess you are working with only one sandbox account.

**Comment by jonnyleigh** [comment] 2017-08-23 19:07
@mickaelpois it happened again today

**Comment by mickaelpois** [comment] 2017-08-31 16:49
Hello @jonnyleigh 

Ok, thanks again for your feedback.
We will have a look at it very soon, we will keep you posted.

Mickaël

**Comment by jonnyleigh** [comment] 2017-08-31 21:09
Thanks @mickaelpois.  It appears to me that the error occurs once a day, the first time I use the SDK in that day.  If I delete the file manually then I am able to use the SDK.  As a workaround I'm going to create a cron job which attempts to delete the temporary file on a daily basis.  Please do let me know if you make any progress on this issue though.

**Comment by hobailey** [comment] 2017-09-15 13:28
I suspect this error is specific to your setup since we're unable to reproduce it and others don't seem to be experiencing it. Since you've also moved to the memory storage approach, I suggest we close this issue :-)

**Closed by hobailey** 2017-09-15 13:28 UTC
